### ISSUE TITLE
Broken video example

### ISSUE THREAD

**Issue by hrueuwuwijeje** [aiexz/itosbot#2]
https://github.com/aiexz/itosbot/assets/169506610/9c2abe77-5595-4ff1-8242-3f12dff13f01

**Comment by hrueuwuwijeje** [comment]
g1h1

**Comment by hrueuwuwijeje** [comment]
hh21y1u

**Comment by aiexz** [comment]
Thanks, I will try to figure out what breaks the video pack creation process

**Comment by aiexz** [comment]
Problem is fixed now. Thank you for the bug report!
